def count_dna(text):
    dna_counts = {}
    for dna in text:
        if dna not in dna_counts:
            dna_counts[dna] = 1
        else:
            dna_counts[dna] += 1
    output = []
    output.append(dna_counts["A"])
    output.append(dna_counts["C"])
    output.append(dna_counts["G"])
    output.append(dna_counts["T"])
    return output
text = "CCCTCGACCACTGGTGGAGAGTTGACCTTGATTAGGCGCGACGAGTGCCCGACTTCGAGTTGAGACCCATACTGTAACCAGCAACGACACTGGTTCTGCCTCGCAGCCATGGTTTGGCCGGTCGCATCCCATTAGGACTCAGTATATTGCTTGTTGCGATCCCCATGGACACTCCGCATCTAAATGACGAAACGCGCATTCGAGGGTTGTTTGGGACGGGTGGCACCACATCTTGCTTCACGCTGCGACCGTATAGAGAACGTCAGACTTTAAAACGATAGTTTGAGCTCTTTAACACTTTGTCAGCCTCTGGCGACCATTACCAGATGGACGGCCGCGTCTCGTTTAAGCGCCTGTGGACTGCTGAGAGATCACCCTGATAGTCTCGTTAGTTCTTAGTCAAGCGACGTCCTGCGGTCAATAATCACTACAGGCACAAAATAACCCCTTAGCCTACAACCAGTCCTGGATTTGGCTAAAAATGTGGACTTTCCTTGCAGTTACTATCAGTAACCAGGCTAAGCTCAAAAACCTGCACCATTAGGAGGCAGAATTATACAGGACGAGCATGGGAGGCTGGTAAGAATGTAGTGTAGATCGGCCTCGCGGTCGGCTCCGCGCGTGCGAACGCCGAGGAGAATGCGTGCCATAGGTAACGGGGTTGTGAACGAACCTCCCGTAAGGGTAATATTGGGACACACGTAAGTACATCGATGATCAGCTACAGAGAGGGCAGCATAGGGTGATTACCGGTTAGAACTGTTTACGGAAACGTCAGTCCTGCTCCTGGTAGTACCTGACGTACATGCTAATTTGACACGCCATTTTTGATAACTAGTCGCCGCGTAG"
print(count_dna(text))